### ISSUE TITLE
Keyboard events are not fired

### ISSUE THREAD

**Issue by Rbn3D** [codecat/SHVDNPro#1]
Not sure why, but keyboard events OnKeyUp / OnKeyDown are never fired.

I'm using and unmodified build from codecat's SHVDNPro on Windows 10 x64.

@codecat I know you are no longer maintaining this, but, can you point me in the right direction? I have no idea what the cause could be.

I tried to open this on my own fork, but looks like forks cannot have issues... 🤕

**Comment by codecat** [comment]
One thing to note - SHVDNPro does not use events, instead you have to override the virtual methods in the Script class. How does your code look like?

**Comment by Rbn3D** [comment]
https://github.com/Rbn3D/CustomCameraV/blob/shvdnpro/Script/CustomCameraV.cs#L363

Yes I now, I looked at the source and noticed that.
No errors in the logs or anything. Just not called.

**Comment by Rbn3D** [comment]
I found this:

https://github.com/codecat/SHVDNPro/blob/master/SHVDNPro/core/Input.cpp#L36

Now it makes more sense, however not sure how to fix and why these objects need to be serializable.
(Lots of stuff to learn)

**Comment by codecat** [comment]
Objects passed to methods in other appdomains require its data to be serializable. I remember this now, yeah. Should be a relatively easy fix, I think.

**Comment by Rbn3D** [comment]
I ended with this

https://github.com/Rbn3D/SHVDNPro/commit/a8f12cf3d5079e666164f65901c02aee5ca030ac

It's a bit hacky but it works.
Do you think it's a good (enough) approach?

I can submit this PR to your repo, but if you can't take care of this I can handle this on my fork. It's up to you. My C++ skills are ok but it's still a new language for me. (I used to be a "managed coder") But I guess I can handle it, with some eventual help.

Do you mind if I provide binary releases on my fork? I will keep the original credits of course... I want to release a new version of Custom Camera V soon...

Looks like everything works now! Thank you for this, it's a great contribution!

**Comment by codecat** [comment]
Considering there's not a whole lot more information passed along the event, I think that's a fair approach. Feel free to PR that. (Maybe without the commented out parts though, not really helpful when we already have Git history 😊)

Also, to be fair, this is mostly managed C++, you're still working with the CLR here so as long as you use `gcnew` etc. instead of `new` without thinking, you should be mostly fine.
