### ISSUE TITLE
Can this be used for multiple cameras setup?

### ISSUE THREAD

**Issue by dbersan** [codecat/SHVDNPro#5]
I found this project through this link: https://gtaforums.com/topic/865719-question-rendering-multiple-cameras/

I was wondering if it's possible to "easily" use this code to render multiple viewports at the same time frame. Let's say you want to add one camera from the front of the car, and another looking to the back of the car, etc. Render those views to a vector of images (relative to the same time frame) and then save it as, say, JPG images on the disk (not necessary, just an example).

**Comment by codecat** [comment]
Are you looking for @Rbn3D's [CustomCameraV](https://github.com/Rbn3D/CustomCameraV)?

**Comment by dbersan** [comment]
> Are you looking for @Rbn3D's [CustomCameraV](https://github.com/Rbn3D/CustomCameraV)?

hmm.. maybe, I guess haha. Do you know if that other project can be used for such goal?

**Comment by codecat** [comment]
Perhaps. They seem to have made a newer version: [CustomCameraVPlus](https://github.com/Rbn3D/CustomCameraVPlus) - it's probably better to ask it there, as SHVDNPro does not have any code specifically for what you're looking for. (Although that doesn't mean it's not possible!)
